"""Initial migration

Revision ID: 7a1ff50a16c3
Revises: 
Create Date: 2026-05-06 17:35:22.301139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1ff50a16c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pieces',
    sa.Column('id_piece', sa.Integer(), nullable=False),
    sa.Column('nom_piece', sa.String(length=100), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('seuil_alerte', sa.Integer(), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_piece')
    )
    op.create_index(op.f('ix_pieces_id_piece'), 'pieces', ['id_piece'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=100), nullable=False),
    sa.Column('prenom_utilisateur', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('premiere_connexion', sa.Boolean(), nullable=True),
    sa.Column('token_reset', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_utilisateur')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id_utilisateur'), 'utilisateurs', ['id_utilisateur'], unique=False)
    op.create_table('administrateurs',
    sa.Column('id_administrateur', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_administrateur')
    )
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('mecaniciens',
    sa.Column('id_mecanicien', sa.Integer(), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_mecanicien'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_mecanicien')
    )
    op.create_table('receptionnistes',
    sa.Column('id_receptionniste', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_receptionniste'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_receptionniste')
    )
    op.create_table('vehicules',
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('numero_chassis', sa.String(length=50), nullable=True),
    sa.Column('immatriculation', sa.String(length=20), nullable=True),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.String(length=4), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_vehicule')
    )
    op.create_index(op.f('ix_vehicules_id_vehicule'), 'vehicules', ['id_vehicule'], unique=False)
    op.create_index(op.f('ix_vehicules_immatriculation'), 'vehicules', ['immatriculation'], unique=True)
    op.create_index(op.f('ix_vehicules_numero_chassis'), 'vehicules', ['numero_chassis'], unique=True)
    op.create_table('interventions',
    sa.Column('id_intervention', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_mecanicien', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mecanicien'], ['utilisateurs.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicules.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_intervention')
    )
    op.create_index(op.f('ix_interventions_id_intervention'), 'interventions', ['id_intervention'], unique=False)
    op.create_table('rendezvous',
    sa.Column('id_rendezvous', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=True),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reponse_admin', sa.Text(), nullable=True),
    sa.Column('date_alternative', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicules.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_rendezvous')
    )
    op.create_index(op.f('ix_rendezvous_id_rendezvous'), 'rendezvous', ['id_rendezvous'], unique=False)
    op.create_table('reparations',
    sa.Column('id_reparation', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('kilometrage', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicules.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_reparation')
    )
    op.create_index(op.f('ix_reparations_id_reparation'), 'reparations', ['id_reparation'], unique=False)
    op.create_index(op.f('ix_reparations_reference'), 'reparations', ['reference'], unique=False)
    op.create_table('avis',
    sa.Column('id_avis', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_intervention', sa.Integer(), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_intervention'], ['interventions.id_intervention'], ),
    sa.PrimaryKeyConstraint('id_avis')
    )
    op.create_index(op.f('ix_avis_id_avis'), 'avis', ['id_avis'], unique=False)
    op.create_table('devis',
    sa.Column('id_devis', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_vehicule', sa.Integer(), nullable=False),
    sa.Column('id_intervention', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('facture_generee', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_intervention'], ['interventions.id_intervention'], ),
    sa.ForeignKeyConstraint(['id_vehicule'], ['vehicules.id_vehicule'], ),
    sa.PrimaryKeyConstraint('id_devis')
    )
    op.create_index(op.f('ix_devis_id_devis'), 'devis', ['id_devis'], unique=False)
    op.create_index(op.f('ix_devis_reference'), 'devis', ['reference'], unique=True)
    op.create_table('factures',
    sa.Column('id_facture', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_intervention', sa.Integer(), nullable=True),
    sa.Column('id_devis', sa.Integer(), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_emission', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_devis'], ['devis.id_devis'], ),
    sa.ForeignKeyConstraint(['id_intervention'], ['interventions.id_intervention'], ),
    sa.PrimaryKeyConstraint('id_facture')
    )
    op.create_index(op.f('ix_factures_id_facture'), 'factures', ['id_facture'], unique=False)
    op.create_index(op.f('ix_factures_reference'), 'factures', ['reference'], unique=True)
    op.create_table('lignes_devis',
    sa.Column('id_ligne_devis', sa.Integer(), nullable=False),
    sa.Column('id_devis', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('id_piece', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_devis'], ['devis.id_devis'], ),
    sa.ForeignKeyConstraint(['id_piece'], ['pieces.id_piece'], ),
    sa.PrimaryKeyConstraint('id_ligne_devis')
    )
    op.create_index(op.f('ix_lignes_devis_id_ligne_devis'), 'lignes_devis', ['id_ligne_devis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lignes_devis_id_ligne_devis'), table_name='lignes_devis')
    op.drop_table('lignes_devis')
    op.drop_index(op.f('ix_factures_reference'), table_name='factures')
    op.drop_index(op.f('ix_factures_id_facture'), table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_devis_reference'), table_name='devis')
    op.drop_index(op.f('ix_devis_id_devis'), table_name='devis')
    op.drop_table('devis')
    op.drop_index(op.f('ix_avis_id_avis'), table_name='avis')
    op.drop_table('avis')
    op.drop_index(op.f('ix_reparations_reference'), table_name='reparations')
    op.drop_index(op.f('ix_reparations_id_reparation'), table_name='reparations')
    op.drop_table('reparations')
    op.drop_index(op.f('ix_rendezvous_id_rendezvous'), table_name='rendezvous')
    op.drop_table('rendezvous')
    op.drop_index(op.f('ix_interventions_id_intervention'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_vehicules_numero_chassis'), table_name='vehicules')
    op.drop_index(op.f('ix_vehicules_immatriculation'), table_name='vehicules')
    op.drop_index(op.f('ix_vehicules_id_vehicule'), table_name='vehicules')
    op.drop_table('vehicules')
    op.drop_table('receptionnistes')
    op.drop_table('mecaniciens')
    op.drop_table('clients')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_utilisateurs_id_utilisateur'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_pieces_id_piece'), table_name='pieces')
    op.drop_table('pieces')
    # ### end Alembic commands ###
